---
- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: "{{user}}"

  tasks:
    - include: tasks/bash.yaml
    - include: tasks/git.yaml
    - include: tasks/packages.yaml
    - include: tasks/hybris.yaml
    - include: tasks/terminator.yaml
    - include: tasks/desktop.yaml
    - include: tasks/visual-studio-code.yaml
    - include: tasks/golang.yaml

