- name: Generate cinnamon config from template
  tags:
      - configurations
      - cinnamon
  template:
        src: tasks/configs/desktop/cinnamon.dconf.template
        dest: /tmp/cinnamon.dconf

- name: Import cinnamon config 
  tags:
      - configurations
      - cinnamon
  shell: dconf load /org/cinnamon/ < /tmp/cinnamon.dconf

- name: Import nemo config 
  tags:
      - configurations
      - cinnamon
  shell: dconf load /org/nemo/ < tasks/configs/desktop/nemo.dconf

- name: Increase max fs notify
  tags:
    - configurations
  become_user: root
  shell: echo fs.inotify.max_user_watches=320000768 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
