- name: Install dnf plugins core
  tags:
    - docker
  become_user: root
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Install docker repo
  tags:
    - docker
  become_user: root
  yum_repository:
    name: Docker-CE-Stable
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.docker.com/linux/fedora/31/$basearch/stable
    gpgkey: gpgkey=https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes
    enabled: yes

- name: Install docker
  tags:
    - docker
  become_user: root
  yum:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Start and enable docker service, if not started
  tags:
    - docker
  become_user: root
  service:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  tags: 
    - docker
  become_user: root
  group:
    name: docker
    state: present

- name: Add user to docker group
  tags: 
    - docker
  become_user: root
  user:
    name: '{{ user }}'
    groups: 'docker'
    append: 'yes'

- name: Add firewall rule for docker0 interface
  tags:
    - docker
  become_user: root
  command: firewall-cmd --permanent --zone=trusted --add-interface=docker0

- name: Test cgroup version 1
  tags:
    - docker
  shell: grep -c "unified_cgroup_hierarchy" /etc/default/grub
  register: test_grep_cgroups
  ignore_errors: true

- name: Update systemd to cgroups v1
  tags:
    - docker
  become_user: root
  lineinfile:
    path: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX=\"[^\"]*)(.*\"$)'
    line: '\1 systemd.unified_cgroup_hierarchy=0\2'
    backrefs: yes
  when: test_grep_cgroups.stdout == "0"

- name: update grub2 config
  tags:
    - docker
  become_user: root
  shell: grub2-mkconfig
  
- name: Tell user to reboot
  tags:
    - docker
  debug:
    msg: "YOU SHOULD RESTART YOUR MACHINE TO CHANGES TAKE EFFECT"