- name: Get latest Go binaries
  tags:
    - go
  become_user: root
  script: tasks/scripts/golang/latest-go.sh
  register: latest_go

- name: Download Go binaries
  tags:
    - go
  get_url:
    url: https://dl.google.com/go/go{{latest_go.stdout}}.linux-amd64.tar.gz
    dest: /tmp/golang.tar.gz

- name: Remove old Go folder
  tags:
    - go
  become_user: root
  file:
    path: /usr/local/go
    state: absent

- name: Unpacking go binaries
  tags:
    - go
  become_user: root
  unarchive:
    src: /tmp/golang.tar.gz
    dest: /usr/local/

- name: Remove tmp binary
  tags:
    - go
  file:
    path: /tmp/golang.tar.gz
    state: absent

    