- name: Insert custom hybris alias on bashrc file
  tags:
    - configurations
  blockinfile:
    path: ~/.bashrc
    insertafter: EOF
    marker: "#{mark} ANSIBLE HYBRIS MANAGED BLOCK"
    block: |
      alias hyECleanAllStart="ant clean all && ./hybrisserver.sh debug"
      alias hyAllStart="ant all && ./hybrisserver.sh debug"
      alias hyDebug="./hybrisserver.sh debug"
      alias clinal="ant clean all"
      alias gitsf="git submodule foreach $1"
      alias gitss="git submodule foreach git status"