- name: Get latest kubectl version
  tags:
    - k8s
  command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
  register: kubectl_version

- name: Get latest kubectl binaries
  tags:
    - k8s
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{kubectl_version.stdout}}/bin/linux/amd64/kubectl
    dest: /tmp/kubectl

- name: Copy kubectl to path 
  tags:
    - k8s
  become_user: root
  copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Remove tmp kubectl binary
  tags:
    - k8s
  file:
    path: /tmp/kubectl
    state: absent
