- name: Install terminator
  tags:
    - packages
  become_user: root
  dnf:
    name: terminator
    state: latest

- name: Copy terminator config folder
  tags:
    - configurations
  command: cp -r tasks/configs/terminator ~/.config/
