- name: Install vscode key
  tags:
    - dev-env
  become_user: root
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode repo
  tags:
    - dev-env
  become_user: root
  shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install vscode
  tags:
    - dev-env
  become_user: root
  dnf:
    name: code
    state: latest