- name: Install vscode key
  tags:
    - dev-env
    - vscode
  become_user: root
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Install vscode repo
  tags:
    - dev-env
    - vscode
  become_user: root
  shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

- name: Install vscode
  tags:
    - dev-env
    - vscode
  become_user: root
  dnf:
    name: code
    state: latest

- name: Install vscode extensions
  tags:
    - vscode
  command: code --install-extension {{ item }}
  with_items:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - k--kato.intellij-idea-keybindings
    - ms-azuretools.vscode-docker
    - redhat.java
    - redhat.vscode-xml
    - VisualStudioExptTeam.vscodeintellicode
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
