[general]
import = [
    "~/.config/alacritty/theme.toml"
]

[window]
decorations = "none"
startup_mode = "Maximized"


[font]
size = 10

[terminal.shell]
program = "zellij"
args = ["--layout", "compact"]
